### ISSUE TITLE
An apostrophe is inserted at the beginning of a yapfed cell

### ISSUE THREAD

**Issue by alexander-pecheny** [jfbercher/yapf_ext#1]
Like shown in the gif:

![](http://i.imgur.com/dsRTKCW.gif)

It happens both when calling yapf via Ctrl-L and via pressing the toolbar button.

**Comment by jfbercher** [comment]
Thanks for your comment. 

This extension is outdated. I have reworked it into `code_prettify`. Can you  give it a try? https://github.com/jfbercher/code_prettify
Installation instructions are at the bottom.

**Comment by alexander-pecheny** [comment]
Unfortunately, the problem persists even with `code_prettify`.

**Comment by jfbercher** [comment]
I definitely can't reproduce. 
Please give more details -- os, jupyter/notebook versions, yapf version. Does this happens for all code or just for this example ? 
Please share an example notebook eg in gist https://gist.github.com/ so that I could try it.

**Comment by alexander-pecheny** [comment]
Ubuntu Trusty
jupyter-client (4.4.0)
jupyter-contrib-core (0.3.0)
jupyter-contrib-nbextensions (0.1.0)
jupyter-core (4.1.1)
jupyter-nbextensions-configurator (0.2.1)
yapf (0.11.1)
notebook (4.2.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2

Happens for all code. Example: https://gist.github.com/peczony/36899292b250de1c6ff382fca9a93785

Though in this case it inserts `"` instead of `'`, which happened with the previous code I tried. So far I haven’t been able to figure out why one symbol is choosed over another.

**Comment by jfbercher** [comment]
@peczony 
The issue was with Python2. In that case, yapf returns a differently encoded string (namely the prefix u is present). Furthermore, depending on what is actually in the string, the result is actually returned between simple or double quotes.  I have tried to account for these two points now.  Thanks for the inputs.  New code in https://github.com/jfbercher/code_prettify.

**Comment by alexander-pecheny** [comment]
Thanks, this issue has been resolved, but I’ve found another one [here](https://github.com/jfbercher/code_prettify/issues/1)
